#!/usr/bin/env bash
# vault-tec configuration — generated by /vault-tec:setup
# Source this file in hook scripts: source "$HOME/.vault-tec/config.sh"

# ── Vault ──────────────────────────────────────────────────
VAULT_PATH=""                    # REQUIRED: absolute path to your vault
VAULT_NAME="My Vault"            # Display name

# ── Plugin ────────────────────────────────────────────────
VAULT_TEC_DIR=""                 # Path to vault-tec plugin directory

# ── Companion ──────────────────────────────────────────────
COMPANION_NAME="Vaultie"         # Your companion's name
COMPANION_VOICE="pre-war"        # pre-war | warm | clinical | custom

# ── Processing ─────────────────────────────────────────────
PROCESSING_DEPTH="standard"      # deep | standard | quick
PIPELINE_CHAINING="suggested"    # manual | suggested | automatic

# ── Thresholds ─────────────────────────────────────────────
INBOX_PRESSURE_THRESHOLD=3       # Items before "PRESSURE" warning
ORPHAN_ALERT_THRESHOLD=5         # Orphans before health alert
MAP_SPLIT_THRESHOLD=35           # Notes before suggesting map split
MAP_MERGE_THRESHOLD=5            # Notes before suggesting map merge
LINK_MINIMUM=2                   # Minimum wiki-links per note

# ── S.P.E.C.I.A.L. Dashboard ──────────────────────────────
SPECIAL_ENABLED=true

# ── Rad Counter (mR weights per item) ─────────────────────
RAD_ORPHAN_WEIGHT=2
RAD_DANGLING_WEIGHT=3
RAD_INBOX_WEIGHT=0.5
RAD_STALE_WEIGHT=1
RAD_SCHEMA_WEIGHT=2

# ── Rad Counter levels ─────────────────────────────────────
RAD_CLEAN=5
RAD_LOW=15
RAD_MODERATE=40
RAD_ELEVATED=80

# ── Bobbleheads ────────────────────────────────────────────
BOBBLEHEADS_ENABLED=true
BOBBLEHEAD_NOTES_TIER1=100       # Intelligence
BOBBLEHEAD_NOTES_TIER2=500       # Endurance
BOBBLEHEAD_NOTES_TIER3=1000      # Strength
BOBBLEHEAD_MAP_DEPTH=30          # Charisma
BOBBLEHEAD_SPRINT_COUNT=10       # Agility
BOBBLEHEAD_EVERGREEN_PCT=50      # Luck

# ── Hooks ──────────────────────────────────────────────────
HOOK_SCHEMA_ENFORCEMENT=true
HOOK_REFERENTIAL_INTEGRITY=true
HOOK_SESSION_BOOKENDS=true
HOOK_PATTERN_INJECTION=true
HOOK_COMPACTION_SNAPSHOT=true
HOOK_FAILURE_LOGGING=true
